baseUrl = "https://anotherlusitano.github.io/"
title = "AnotherLusitano"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[services]
[services.disqus]
disqusShortname = "anotherlusitano"

[markup.highlight]
style = "github-dark"

[params]
  author = "João Ribeiro"
  info = "Student and Linux enthusiast"
  description = "João Ribeiro's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/anotherlusitano/"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 2
  url = "mailto:joao.rosado.ribeiro@gmail.com"
[[params.social]]
  name = "Kofi"
  icon = "fa-solid fa-circle-dollar-to-slot fa-2x"
  weight = 3
  url = "https://ko-fi.com/anotherlusitano"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
